repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --no-sort]
    exclude: ^poetry.lock$
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 1.3.1
  hooks:
  - id: tox-ini-fmt

- repo: https://github.com/ariebovenberg/slotscheck
  rev: v0.17.3
  hooks:
  - id: slotscheck
    language: system
    exclude: ^(?!pandoc_latex_environment.py)

- repo: https://github.com/dosisod/refurb
  rev: v2.0.0
  hooks:
  - id: refurb

- repo: https://github.com/isidentical/teyit
  rev: 0.4.3
  hooks:
  - id: teyit

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.3
  hooks:
  - id: ruff
    language: system
    exclude: ^(?!pandoc_latex_environment.py)

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black-jupyter
    args: [--config=pyproject.toml, pandoc_latex_environment.py, tests]

- repo: https://github.com/PyCQA/doc8/
  rev: v1.1.1
  hooks:
  - id: doc8
    args: [docs]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    language: system
    exclude: ^(?!pandoc_latex_environment.py)

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language: system
    exclude: ^(?!pandoc_latex_environment.py)

- repo: https://github.com/pylint-dev/pylint
  rev: v3.1.0
  hooks:
  - id: pylint
    language: system
    exclude: ^(?!galactic/algebras/)
