# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        pandoc-version: ['3.5']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: Install dependencies
      run: |
        wget https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc-version }}/pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
        sudo dpkg -i ./pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
    - name: Test
      run: |
        hatch test -py ${{ matrix.python-version }}

  pandoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        pandoc-version: [2.11.4, '2.12', '2.13', 2.14.2, '2.15', 2.16.2, 2.17.1.1, '2.18', 2.19.2, 3.0.1, 3.1.13, 3.2.1, '3.3', '3.4', '3.5']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: Install dependencies
      run: |
        wget https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc-version }}/pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
        sudo dpkg -i ./pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
    - name: Test
      run: |
        hatch test

  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        pandoc-version: ['3.5']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: Install dependencies
      run: |
        wget https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc-version }}/pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
        sudo dpkg -i ./pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
    - name: Static check
      run: |
        hatch fmt --check
    - name: Dynamic check
      run: |
        hatch run lint:check

  cov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        pandoc-version: ['3.5']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: Install dependencies
      run: |
        wget https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc-version }}/pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
        sudo dpkg -i ./pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
    - name: Test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |-
        hatch test --cover
        hatch run pip install coveralls
        hatch run coveralls
